ancine:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PWD') }}"
      database: "{{ env_var('DB_DATABASE') }}"
      schema: public