services:
  postgres:
    image: postgres
    container_name: ancine-database
    environment:
      POSTGRES_PASSWORD: ancinedb
      POSTGRES_DB: metabase
    restart: always

  metabase:
    image: metabase/metabase
    container_name: ancine-metabase
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: ancinedb
      MB_DB_HOST: postgres
    restart: always
